package com.test;

class Customer{
	public String name;
	public long balance;
}

public class ExceptionTest {

	public static void main(String[] args) throws Exception {

		System.out.println("예외상황을 발생시켜요!");

//		try {
//			int result = 10 / 0; // 문법적인 오류는 없다. 하지만 runtime에 이상한 상황(exception)이  발생
//		} catch(NullPointerException e) {
//			System.out.println("널포인터 익셉션!!"); // 원래는 sysout이 아니라 이 문제를 해결해줄수 있는 logic code들이 나오는 위치이다.
//		} catch(Exception e) {
//			System.out.println("수학연산 잘못됬어요!");
//		// 원래는 예외상황처리코드가 나와야한다.
//		} finally {
//			// 얘는 무조건 수행딘다.(예외가 있거나 없거나...)
//		}
		System.out.println("여기는 출력되나요!");
//		
	}
//	

		
	}



